
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports tx]

set_property PACKAGE_PIN N5 [get_ports rx]
set_property PACKAGE_PIN P17 [get_ports sys_clk]
set_property PACKAGE_PIN T4 [get_ports tx]

#input for power
set_property PACKAGE_PIN R17 [get_ports power_off]
set_property PACKAGE_PIN U4 [get_ports power_on]
set_property IOSTANDARD LVCMOS33 [get_ports power_off]
set_property IOSTANDARD LVCMOS33 [get_ports power_on]


#input for mode
set_property PACKAGE_PIN P4 [get_ports {mode[2]}]
set_property PACKAGE_PIN P3 [get_ports {mode[1]}]
set_property PACKAGE_PIN P2 [get_ports {mode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[0]}]

#input for turn left and right 
set_property PACKAGE_PIN V1 [get_ports turn_left]
set_property PACKAGE_PIN R11 [get_ports turn_right]
set_property IOSTANDARD LVCMOS33 [get_ports turn_left]
set_property IOSTANDARD LVCMOS33 [get_ports turn_right]
set_property PACKAGE_PIN R15 [get_ports go_strait]
set_property IOSTANDARD LVCMOS33 [get_ports go_strait]

#output for test state
set_property PACKAGE_PIN F6 [get_ports {test[3]}]
set_property PACKAGE_PIN G4 [get_ports {test[2]}]
set_property PACKAGE_PIN G3 [get_ports {test[1]}]
set_property PACKAGE_PIN J4 [get_ports {test[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test[0]}]

#input for control
set_property PACKAGE_PIN R1 [get_ports reverse_gear_shift]
set_property PACKAGE_PIN N4 [get_ports clutch]
set_property PACKAGE_PIN M4 [get_ports brake]
set_property PACKAGE_PIN R2 [get_ports throttle]
set_property IOSTANDARD LVCMOS33 [get_ports reverse_gear_shift]
set_property IOSTANDARD LVCMOS33 [get_ports clutch]
set_property IOSTANDARD LVCMOS33 [get_ports brake]
set_property IOSTANDARD LVCMOS33 [get_ports throttle]

#ouput for test direction
set_property PACKAGE_PIN K1 [get_ports direction_left_light]
set_property PACKAGE_PIN K3 [get_ports direction_right_light]
set_property IOSTANDARD LVCMOS33 [get_ports direction_left_light]
set_property IOSTANDARD LVCMOS33 [get_ports direction_right_light]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sel}]
#set_property PACKAGE_PIN P5 [get_ports {sel}]
#set_property PACKAGE_PIN R2 [get_ports {sw[3]}]
#set_property PACKAGE_PIN M4 [get_ports {sw[2]}]
#set_property PACKAGE_PIN N4 [get_ports {sw[1]}]
#set_property PACKAGE_PIN R1 [get_ports {sw[0]}]
set_property PACKAGE_PIN G2 [get_ports {seg_en[7]}]
set_property PACKAGE_PIN C2 [get_ports {seg_en[6]}]
set_property PACKAGE_PIN C1 [get_ports {seg_en[5]}]
set_property PACKAGE_PIN H1 [get_ports {seg_en[4]}]
set_property PACKAGE_PIN G1 [get_ports {seg_en[3]}]
set_property PACKAGE_PIN F1 [get_ports {seg_en[2]}]
set_property PACKAGE_PIN E1 [get_ports {seg_en[1]}]
set_property PACKAGE_PIN G6 [get_ports {seg_en[0]}]
set_property PACKAGE_PIN B4 [get_ports {seg_out0[7]}]
set_property PACKAGE_PIN A4 [get_ports {seg_out0[6]}]
set_property PACKAGE_PIN A3 [get_ports {seg_out0[5]}]
set_property PACKAGE_PIN B1 [get_ports {seg_out0[4]}]
set_property PACKAGE_PIN A1 [get_ports {seg_out0[3]}]
set_property PACKAGE_PIN B3 [get_ports {seg_out0[2]}]
set_property PACKAGE_PIN B2 [get_ports {seg_out0[1]}]
set_property PACKAGE_PIN D5 [get_ports {seg_out0[0]}]
set_property PACKAGE_PIN D4 [get_ports {seg_out1[7]}]
set_property PACKAGE_PIN E3 [get_ports {seg_out1[6]}]
set_property PACKAGE_PIN D3 [get_ports {seg_out1[5]}]
set_property PACKAGE_PIN F4 [get_ports {seg_out1[4]}]
set_property PACKAGE_PIN F3 [get_ports {seg_out1[3]}]
set_property PACKAGE_PIN E2 [get_ports {seg_out1[2]}]
set_property PACKAGE_PIN D2 [get_ports {seg_out1[1]}]
set_property PACKAGE_PIN H2 [get_ports {seg_out1[0]}]